name: Update QA Stand
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ["self-hosted", "k8s-prod"]
    strategy:
      matrix:
        node-version: [16.15.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version}}
      - name: Install necessary versions of tools
        run: |
          npm install yarn@1.22.10 -g
          npm install lerna@3.4.3 -g
      - name: Install modules
        run: |
          yarn install --ignore-engines
      - name: Build
        run: |
          yarn build-gov
      - name: Deploy to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{vars.DAO_QA_S3_BUCKET}}
          AWS_ACCESS_KEY_ID: ${{secrets.DAO_QA_AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.DAO_QA_AWS_SECRET_ACCESS_KEY  }}
          AWS_REGION: ${{vars.DAO_QA_S3_BUCKET_REGION}}
          SOURCE_DIR: "build/governance"
